default: &default
  adapter: postgresql

production:
  adapter: postgresql
  database: db/production

development:

  development:
  <<: *default
  database: 'cars'
  username: 'rick'
  password: 'carsdb'